// Catch-all stubs for remaining Steamworks.NET symbols. All return 0/NULL.

#include <stdint.h>
#include <string.h>

intptr_t SteamAPI_ISteamFriends_ActivateGameOverlayRemotePlayTogetherInviteDialog() { return 0; }
intptr_t SteamAPI_ISteamFriends_GetFriendCountFromSource() { return 0; }
intptr_t SteamAPI_ISteamFriends_GetFriendFromSourceByIndex() { return 0; }
intptr_t SteamAPI_ISteamFriends_GetFriendPersonaNameHistory() { return 0; }
intptr_t SteamAPI_ISteamFriends_GetProfileItemPropertyString() { return 0; }
intptr_t SteamAPI_ISteamFriends_GetProfileItemPropertyUint() { return 0; }
intptr_t SteamAPI_ISteamFriends_SetInGameVoiceSpeaking() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_AcceptGame() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_AddGameSearchParams() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_CancelRequestPlayersForGame() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_DeclineGame() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_EndGame() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_EndGameSearch() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_HostConfirmGameStart() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_RequestPlayersForGame() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_RetrieveConnectionDetails() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_SearchForGameSolo() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_SearchForGameWithLobby() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_SetConnectionDetails() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_SetGameHostParams() { return 0; }
intptr_t SteamAPI_ISteamGameSearch_SubmitPlayerResult() { return 0; }
intptr_t SteamAPI_ISteamGameServer_AssociateWithClan() { return 0; }
intptr_t SteamAPI_ISteamGameServer_BeginAuthSession() { return 0; }
intptr_t SteamAPI_ISteamGameServer_BLoggedOn() { return 0; }
intptr_t SteamAPI_ISteamGameServer_BSecure() { return 0; }
intptr_t SteamAPI_ISteamGameServer_BUpdateUserData() { return 0; }
intptr_t SteamAPI_ISteamGameServer_CancelAuthTicket() { return 0; }
intptr_t SteamAPI_ISteamGameServer_ClearAllKeyValues() { return 0; }
intptr_t SteamAPI_ISteamGameServer_ComputeNewPlayerCompatibility() { return 0; }
intptr_t SteamAPI_ISteamGameServer_CreateUnauthenticatedUserConnection() { return 0; }
intptr_t SteamAPI_ISteamGameServer_EndAuthSession() { return 0; }
intptr_t SteamAPI_ISteamGameServer_GetAuthSessionTicket() { return 0; }
intptr_t SteamAPI_ISteamGameServer_GetGameplayStats() { return 0; }
intptr_t SteamAPI_ISteamGameServer_GetNextOutgoingPacket() { return 0; }
intptr_t SteamAPI_ISteamGameServer_GetPublicIP() { return 0; }
intptr_t SteamAPI_ISteamGameServer_GetServerReputation() { return 0; }
intptr_t SteamAPI_ISteamGameServer_GetSteamID() { return 0; }
intptr_t SteamAPI_ISteamGameServer_HandleIncomingPacket() { return 0; }
intptr_t SteamAPI_ISteamGameServer_LogOff() { return 0; }
intptr_t SteamAPI_ISteamGameServer_LogOn() { return 0; }
intptr_t SteamAPI_ISteamGameServer_LogOnAnonymous() { return 0; }
intptr_t SteamAPI_ISteamGameServer_RequestUserGroupStatus() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SendUserConnectAndAuthenticate_DEPRECATED() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SendUserDisconnect_DEPRECATED() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetAdvertiseServerActive() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetBotPlayerCount() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetDedicatedServer() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetGameData() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetGameDescription() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetGameTags() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetKeyValue() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetMapName() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetMaxPlayerCount() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetModDir() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetPasswordProtected() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetProduct() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetRegion() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetServerName() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetSpectatorPort() { return 0; }
intptr_t SteamAPI_ISteamGameServer_SetSpectatorServerName() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_ClearUserAchievement() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_GetUserAchievement() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_GetUserStatFloat() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_GetUserStatInt32() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_RequestUserStats() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_SetUserAchievement() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_SetUserStatFloat() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_SetUserStatInt32() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_StoreUserStats() { return 0; }
intptr_t SteamAPI_ISteamGameServerStats_UpdateUserAvgRateStat() { return 0; }
intptr_t SteamAPI_ISteamGameServer_UserHasLicenseForApp() { return 0; }
intptr_t SteamAPI_ISteamGameServer_WasRestartRequested() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_AddHeader() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_AllowStartRequest() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_CopyToClipboard() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_CreateBrowser() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_ExecuteJavascript() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_FileLoadDialogResponse() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_Find() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_GetLinkAtPosition() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_GoBack() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_GoForward() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_JSDialogResponse() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_KeyChar() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_KeyDown() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_KeyUp() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_LoadURL() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_MouseDoubleClick() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_MouseDown() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_MouseMove() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_MouseUp() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_MouseWheel() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_OpenDeveloperTools() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_PasteFromClipboard() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_Reload() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_RemoveBrowser() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetBackgroundMode() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetCookie() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetDPIScalingFactor() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetHorizontalScroll() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetKeyFocus() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetPageScaleFactor() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetSize() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_SetVerticalScroll() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_StopFind() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_StopLoad() { return 0; }
intptr_t SteamAPI_ISteamHTMLSurface_ViewSource() { return 0; }
intptr_t SteamAPI_ISteamHTTP_CreateCookieContainer() { return 0; }
intptr_t SteamAPI_ISteamHTTP_CreateHTTPRequest() { return 0; }
intptr_t SteamAPI_ISteamHTTP_DeferHTTPRequest() { return 0; }
intptr_t SteamAPI_ISteamHTTP_GetHTTPDownloadProgressPct() { return 0; }
intptr_t SteamAPI_ISteamHTTP_GetHTTPRequestWasTimedOut() { return 0; }
intptr_t SteamAPI_ISteamHTTP_GetHTTPResponseBodyData() { return 0; }
intptr_t SteamAPI_ISteamHTTP_GetHTTPResponseBodySize() { return 0; }
intptr_t SteamAPI_ISteamHTTP_GetHTTPResponseHeaderSize() { return 0; }
intptr_t SteamAPI_ISteamHTTP_GetHTTPResponseHeaderValue() { return 0; }
intptr_t SteamAPI_ISteamHTTP_GetHTTPStreamingResponseBodyData() { return 0; }
intptr_t SteamAPI_ISteamHTTP_PrioritizeHTTPRequest() { return 0; }
intptr_t SteamAPI_ISteamHTTP_ReleaseCookieContainer() { return 0; }
intptr_t SteamAPI_ISteamHTTP_ReleaseHTTPRequest() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SendHTTPRequest() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SendHTTPRequestAndStreamResponse() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetCookie() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestAbsoluteTimeoutMS() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestContextValue() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestCookieContainer() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestGetOrPostParameter() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestHeaderValue() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestNetworkActivityTimeout() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestRawPostBody() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestRequiresVerifiedCertificate() { return 0; }
intptr_t SteamAPI_ISteamHTTP_SetHTTPRequestUserAgentInfo() { return 0; }
intptr_t SteamAPI_ISteamInventory_AddPromoItem() { return 0; }
intptr_t SteamAPI_ISteamInventory_AddPromoItems() { return 0; }
intptr_t SteamAPI_ISteamInventory_CheckResultSteamID() { return 0; }
intptr_t SteamAPI_ISteamInventory_ConsumeItem() { return 0; }
intptr_t SteamAPI_ISteamInventory_DeserializeResult() { return 0; }
intptr_t SteamAPI_ISteamInventory_DestroyResult() { return 0; }
intptr_t SteamAPI_ISteamInventory_ExchangeItems() { return 0; }
intptr_t SteamAPI_ISteamInventory_GenerateItems() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetAllItems() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetEligiblePromoItemDefinitionIDs() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetItemDefinitionIDs() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetItemDefinitionProperty() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetItemPrice() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetItemsByID() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetItemsWithPrices() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetNumItemsWithPrices() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetResultItemProperty() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetResultItems() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetResultStatus() { return 0; }
intptr_t SteamAPI_ISteamInventory_GetResultTimestamp() { return 0; }
intptr_t SteamAPI_ISteamInventory_GrantPromoItems() { return 0; }
intptr_t SteamAPI_ISteamInventory_InspectItem() { return 0; }
intptr_t SteamAPI_ISteamInventory_LoadItemDefinitions() { return 0; }
intptr_t SteamAPI_ISteamInventory_RemoveProperty() { return 0; }
intptr_t SteamAPI_ISteamInventory_RequestEligiblePromoItemDefinitionsIDs() { return 0; }
intptr_t SteamAPI_ISteamInventory_RequestPrices() { return 0; }
intptr_t SteamAPI_ISteamInventory_SendItemDropHeartbeat() { return 0; }
intptr_t SteamAPI_ISteamInventory_SerializeResult() { return 0; }
intptr_t SteamAPI_ISteamInventory_SetPropertyBool() { return 0; }
intptr_t SteamAPI_ISteamInventory_SetPropertyFloat() { return 0; }
intptr_t SteamAPI_ISteamInventory_SetPropertyInt64() { return 0; }
intptr_t SteamAPI_ISteamInventory_SetPropertyString() { return 0; }
intptr_t SteamAPI_ISteamInventory_StartPurchase() { return 0; }
intptr_t SteamAPI_ISteamInventory_StartUpdateProperties() { return 0; }
intptr_t SteamAPI_ISteamInventory_SubmitUpdateProperties() { return 0; }
intptr_t SteamAPI_ISteamInventory_TradeItems() { return 0; }
intptr_t SteamAPI_ISteamInventory_TransferItemQuantity() { return 0; }
intptr_t SteamAPI_ISteamInventory_TriggerItemDrop() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddFavoriteGame() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddRequestLobbyListCompatibleMembersFilter() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddRequestLobbyListDistanceFilter() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddRequestLobbyListFilterSlotsAvailable() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddRequestLobbyListNearValueFilter() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddRequestLobbyListNumericalFilter() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddRequestLobbyListResultCountFilter() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_AddRequestLobbyListStringFilter() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_CreateLobby() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_DeleteLobbyData() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetFavoriteGame() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetFavoriteGameCount() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyByIndex() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyChatEntry() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyData() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyDataByIndex() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyDataCount() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyGameServer() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyMemberByIndex() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyMemberData() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyMemberLimit() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetLobbyOwner() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_GetNumLobbyMembers() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_InviteUserToLobby() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_JoinLobby() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_LeaveLobby() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_RemoveFavoriteGame() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_RequestLobbyData() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_RequestLobbyList() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SendLobbyChatMsg() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_CancelQuery() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_CancelServerQuery() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_GetServerCount() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_GetServerDetails() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_IsRefreshing() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_PingServer() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_PlayerDetails() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RefreshQuery() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RefreshServer() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_ReleaseRequest() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RequestFavoritesServerList() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RequestFriendsServerList() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RequestHistoryServerList() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RequestInternetServerList() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RequestLANServerList() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_RequestSpectatorServerList() { return 0; }
intptr_t SteamAPI_ISteamMatchmakingServers_ServerRules() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLinkedLobby() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLobbyData() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLobbyGameServer() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLobbyJoinable() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLobbyMemberData() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLobbyMemberLimit() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLobbyOwner() { return 0; }
intptr_t SteamAPI_ISteamMatchmaking_SetLobbyType() { return 0; }
intptr_t SteamAPI_ISteamMusic_BIsEnabled() { return 0; }
intptr_t SteamAPI_ISteamMusic_BIsPlaying() { return 0; }
intptr_t SteamAPI_ISteamMusic_GetPlaybackStatus() { return 0; }
intptr_t SteamAPI_ISteamMusic_GetVolume() { return 0; }
intptr_t SteamAPI_ISteamMusic_Pause() { return 0; }
intptr_t SteamAPI_ISteamMusic_Play() { return 0; }
intptr_t SteamAPI_ISteamMusic_PlayNext() { return 0; }
intptr_t SteamAPI_ISteamMusic_PlayPrevious() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_BActivationSuccess() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_BIsCurrentMusicRemote() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_CurrentEntryDidChange() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_CurrentEntryIsAvailable() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_CurrentEntryWillChange() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_DeregisterSteamMusicRemote() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_EnableLooped() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_EnablePlaylists() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_EnablePlayNext() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_EnablePlayPrevious() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_EnableQueue() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_EnableShuffled() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_PlaylistDidChange() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_PlaylistWillChange() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_QueueDidChange() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_QueueWillChange() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_RegisterSteamMusicRemote() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_ResetPlaylistEntries() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_ResetQueueEntries() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_SetCurrentPlaylistEntry() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_SetCurrentQueueEntry() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_SetDisplayName() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_SetPlaylistEntry() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_SetPNGIcon_64x64() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_SetQueueEntry() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_UpdateCurrentEntryCoverArt() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_UpdateCurrentEntryElapsedSeconds() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_UpdateCurrentEntryText() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_UpdateLooped() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_UpdatePlaybackStatus() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_UpdateShuffled() { return 0; }
intptr_t SteamAPI_ISteamMusicRemote_UpdateVolume() { return 0; }
intptr_t SteamAPI_ISteamMusic_SetVolume() { return 0; }
intptr_t SteamAPI_ISteamNetworking_AcceptP2PSessionWithUser() { return 0; }
intptr_t SteamAPI_ISteamNetworking_AllowP2PPacketRelay() { return 0; }
intptr_t SteamAPI_ISteamNetworking_CloseP2PChannelWithUser() { return 0; }
intptr_t SteamAPI_ISteamNetworking_CloseP2PSessionWithUser() { return 0; }
intptr_t SteamAPI_ISteamNetworking_CreateConnectionSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_CreateListenSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_CreateP2PConnectionSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_DestroyListenSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_DestroySocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_GetListenSocketInfo() { return 0; }
intptr_t SteamAPI_ISteamNetworking_GetMaxPacketSize() { return 0; }
intptr_t SteamAPI_ISteamNetworking_GetP2PSessionState() { return 0; }
intptr_t SteamAPI_ISteamNetworking_GetSocketConnectionType() { return 0; }
intptr_t SteamAPI_ISteamNetworking_GetSocketInfo() { return 0; }
intptr_t SteamAPI_ISteamNetworking_IsDataAvailable() { return 0; }
intptr_t SteamAPI_ISteamNetworking_IsDataAvailableOnSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_IsP2PPacketAvailable() { return 0; }
intptr_t SteamAPI_ISteamNetworkingMessages_AcceptSessionWithUser() { return 0; }
intptr_t SteamAPI_ISteamNetworkingMessages_CloseChannelWithUser() { return 0; }
intptr_t SteamAPI_ISteamNetworkingMessages_CloseSessionWithUser() { return 0; }
intptr_t SteamAPI_ISteamNetworkingMessages_GetSessionConnectionInfo() { return 0; }
intptr_t SteamAPI_ISteamNetworkingMessages_ReceiveMessagesOnChannel() { return 0; }
intptr_t SteamAPI_ISteamNetworkingMessages_SendMessageToUser() { return 0; }
intptr_t SteamAPI_ISteamNetworking_ReadP2PPacket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_RetrieveData() { return 0; }
intptr_t SteamAPI_ISteamNetworking_RetrieveDataFromSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_SendDataOnSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworking_SendP2PPacket() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_AcceptConnection() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_BeginAsyncRequestFakeIP() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CloseConnection() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CloseListenSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ConfigureConnectionLanes() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ConnectByIPAddress() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ConnectP2P() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ConnectP2PCustomSignaling() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ConnectToHostedDedicatedServer() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CreateFakeUDPPort() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CreateHostedDedicatedServerListenSocket() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CreateListenSocketIP() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CreateListenSocketP2P() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CreateListenSocketP2PFakeIP() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CreatePollGroup() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_CreateSocketPair() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_DestroyPollGroup() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_FindRelayAuthTicketForServer() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_FlushMessagesOnConnection() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetAuthenticationStatus() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetCertificateRequest() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetConnectionInfo() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetConnectionName() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetConnectionRealTimeStatus() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetConnectionUserData() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetDetailedConnectionStatus() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetFakeIP() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetGameCoordinatorServerLogin() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetHostedDedicatedServerAddress() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetHostedDedicatedServerPOPID() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetHostedDedicatedServerPort() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetIdentity() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetListenSocketAddress() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_GetRemoteFakeIPForConnection() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ReceivedP2PCustomSignal() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ReceivedRelayAuthTicket() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ReceiveMessagesOnConnection() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ReceiveMessagesOnPollGroup() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_ResetIdentity() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_RunCallbacks() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_SendMessages() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_SendMessageToConnection() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_SetCertificate() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_SetConnectionName() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_SetConnectionPollGroup() { return 0; }
intptr_t SteamAPI_ISteamNetworkingSockets_SetConnectionUserData() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_AllocateMessage() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_CheckPingDataUpToDate() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_ConvertPingLocationToString() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_EstimatePingTimeBetweenTwoLocations() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_EstimatePingTimeFromLocalHost() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetConfigValue() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetConfigValueInfo() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetDirectPingToPOP() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetIPv4FakeIPType() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetLocalPingLocation() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetLocalTimestamp() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetPingToDataCenter() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetPOPCount() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetPOPList() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetRealIdentityForFakeIP() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_GetRelayNetworkStatus() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_InitRelayNetworkAccess() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_IsFakeIPv4() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_IterateGenericEditableConfigValues() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_ParsePingLocationString() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_SetConfigValue() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_SetDebugOutputFunction() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIdentity_ParseString() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIdentity_ToString() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIPAddr_GetFakeIPType() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIPAddr_ParseString() { return 0; }
intptr_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIPAddr_ToString() { return 0; }
intptr_t SteamAPI_ISteamParentalSettings_BIsAppBlocked() { return 0; }
intptr_t SteamAPI_ISteamParentalSettings_BIsAppInBlockList() { return 0; }
intptr_t SteamAPI_ISteamParentalSettings_BIsFeatureBlocked() { return 0; }
intptr_t SteamAPI_ISteamParentalSettings_BIsFeatureInBlockList() { return 0; }
intptr_t SteamAPI_ISteamParentalSettings_BIsParentalLockEnabled() { return 0; }
intptr_t SteamAPI_ISteamParentalSettings_BIsParentalLockLocked() { return 0; }
intptr_t SteamAPI_ISteamParties_CancelReservation() { return 0; }
intptr_t SteamAPI_ISteamParties_ChangeNumOpenSlots() { return 0; }
intptr_t SteamAPI_ISteamParties_CreateBeacon() { return 0; }
intptr_t SteamAPI_ISteamParties_DestroyBeacon() { return 0; }
intptr_t SteamAPI_ISteamParties_GetAvailableBeaconLocations() { return 0; }
intptr_t SteamAPI_ISteamParties_GetBeaconByIndex() { return 0; }
intptr_t SteamAPI_ISteamParties_GetBeaconDetails() { return 0; }
intptr_t SteamAPI_ISteamParties_GetBeaconLocationData() { return 0; }
intptr_t SteamAPI_ISteamParties_GetNumActiveBeacons() { return 0; }
intptr_t SteamAPI_ISteamParties_GetNumAvailableBeaconLocations() { return 0; }
intptr_t SteamAPI_ISteamParties_JoinParty() { return 0; }
intptr_t SteamAPI_ISteamParties_OnReservationCompleted() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_BGetSessionClientResolution() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_BSendRemotePlayTogetherInvite() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_BStartRemotePlayTogether() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_GetSessionClientFormFactor() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_GetSessionClientName() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_GetSessionCount() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_GetSessionID() { return 0; }
intptr_t SteamAPI_ISteamRemotePlay_GetSessionSteamID() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_CommitPublishedFileUpdate() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_CreatePublishedFileUpdateRequest() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_DeletePublishedFile() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_EnumeratePublishedFilesByUserAction() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_EnumeratePublishedWorkshopFiles() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_EnumerateUserPublishedFiles() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_EnumerateUserSharedWorkshopFiles() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_EnumerateUserSubscribedFiles() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_FileShare() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_FileWriteStreamCancel() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_FileWriteStreamClose() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_FileWriteStreamOpen() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_FileWriteStreamWriteChunk() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetCachedUGCCount() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetCachedUGCHandle() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetLocalFileChange() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetLocalFileChangeCount() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetPublishedFileDetails() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetPublishedItemVoteDetails() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetUGCDetails() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetUGCDownloadProgress() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_GetUserPublishedItemVoteDetails() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_PublishVideo() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_PublishWorkshopFile() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_SetSyncPlatforms() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_SetUserPublishedFileAction() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_SubscribePublishedFile() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UGCDownload() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UGCDownloadToLocation() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UGCRead() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UnsubscribePublishedFile() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileDescription() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileFile() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFilePreviewFile() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileSetChangeDescription() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTags() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTitle() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileVisibility() { return 0; }
intptr_t SteamAPI_ISteamRemoteStorage_UpdateUserPublishedItemVote() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_AddScreenshotToLibrary() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_AddVRScreenshotToLibrary() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_HookScreenshots() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_IsScreenshotsHooked() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_SetLocation() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_TagPublishedFile() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_TagUser() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_TriggerScreenshot() { return 0; }
intptr_t SteamAPI_ISteamScreenshots_WriteScreenshot() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddAppDependency() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddContentDescriptor() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddDependency() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddExcludedTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddItemKeyValueTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddItemPreviewFile() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddItemPreviewVideo() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddItemToFavorites() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddRequiredKeyValueTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddRequiredTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_AddRequiredTagGroup() { return 0; }
intptr_t SteamAPI_ISteamUGC_BInitWorkshopForGameServer() { return 0; }
intptr_t SteamAPI_ISteamUGC_CreateItem() { return 0; }
intptr_t SteamAPI_ISteamUGC_CreateQueryAllUGCRequestCursor() { return 0; }
intptr_t SteamAPI_ISteamUGC_CreateQueryAllUGCRequestPage() { return 0; }
intptr_t SteamAPI_ISteamUGC_CreateQueryUGCDetailsRequest() { return 0; }
intptr_t SteamAPI_ISteamUGC_CreateQueryUserUGCRequest() { return 0; }
intptr_t SteamAPI_ISteamUGC_DeleteItem() { return 0; }
intptr_t SteamAPI_ISteamUGC_DownloadItem() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetAppDependencies() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetItemDownloadInfo() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetItemInstallInfo() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetItemState() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetItemUpdateProgress() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetNumSubscribedItems() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetNumSupportedGameVersions() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryFirstUGCKeyValueTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCAdditionalPreview() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCChildren() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCContentDescriptors() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCKeyValueTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCMetadata() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCNumAdditionalPreviews() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCNumKeyValueTags() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCNumTags() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCPreviewURL() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCResult() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCStatistic() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetQueryUGCTagDisplayName() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetSubscribedItems() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetSupportedGameVersionData() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetUserContentDescriptorPreferences() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetUserItemVote() { return 0; }
intptr_t SteamAPI_ISteamUGC_GetWorkshopEULAStatus() { return 0; }
intptr_t SteamAPI_ISteamUGC_ReleaseQueryUGCRequest() { return 0; }
intptr_t SteamAPI_ISteamUGC_RemoveAllItemKeyValueTags() { return 0; }
intptr_t SteamAPI_ISteamUGC_RemoveAppDependency() { return 0; }
intptr_t SteamAPI_ISteamUGC_RemoveContentDescriptor() { return 0; }
intptr_t SteamAPI_ISteamUGC_RemoveDependency() { return 0; }
intptr_t SteamAPI_ISteamUGC_RemoveItemFromFavorites() { return 0; }
intptr_t SteamAPI_ISteamUGC_RemoveItemKeyValueTags() { return 0; }
intptr_t SteamAPI_ISteamUGC_RemoveItemPreview() { return 0; }
intptr_t SteamAPI_ISteamUGC_RequestUGCDetails() { return 0; }
intptr_t SteamAPI_ISteamUGC_SendQueryUGCRequest() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetAdminQuery() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetAllowCachedResponse() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetAllowLegacyUpload() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetCloudFileNameFilter() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemContent() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemDescription() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemMetadata() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemPreview() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemTags() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemTitle() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemUpdateLanguage() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetItemVisibility() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetLanguage() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetMatchAnyTag() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetRankedByTrendDays() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetRequiredGameVersions() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnAdditionalPreviews() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnChildren() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnKeyValueTags() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnLongDescription() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnMetadata() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnOnlyIDs() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnPlaytimeStats() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetReturnTotalOnly() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetSearchText() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetTimeCreatedDateRange() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetTimeUpdatedDateRange() { return 0; }
intptr_t SteamAPI_ISteamUGC_SetUserItemVote() { return 0; }
intptr_t SteamAPI_ISteamUGC_ShowWorkshopEULA() { return 0; }
intptr_t SteamAPI_ISteamUGC_StartItemUpdate() { return 0; }
intptr_t SteamAPI_ISteamUGC_StartPlaytimeTracking() { return 0; }
intptr_t SteamAPI_ISteamUGC_StopPlaytimeTracking() { return 0; }
intptr_t SteamAPI_ISteamUGC_StopPlaytimeTrackingForAllItems() { return 0; }
intptr_t SteamAPI_ISteamUGC_SubmitItemUpdate() { return 0; }
intptr_t SteamAPI_ISteamUGC_SubscribeItem() { return 0; }
intptr_t SteamAPI_ISteamUGC_SuspendDownloads() { return 0; }
intptr_t SteamAPI_ISteamUGC_UnsubscribeItem() { return 0; }
intptr_t SteamAPI_ISteamUGC_UpdateItemPreviewFile() { return 0; }
intptr_t SteamAPI_ISteamUGC_UpdateItemPreviewVideo() { return 0; }
intptr_t SteamAPI_ISteamUser_AdvertiseGame() { return 0; }
intptr_t SteamAPI_ISteamUser_BeginAuthSession() { return 0; }
intptr_t SteamAPI_ISteamUser_BIsBehindNAT() { return 0; }
intptr_t SteamAPI_ISteamUser_BIsPhoneIdentifying() { return 0; }
intptr_t SteamAPI_ISteamUser_BIsPhoneRequiringVerification() { return 0; }
intptr_t SteamAPI_ISteamUser_BIsPhoneVerified() { return 0; }
intptr_t SteamAPI_ISteamUser_BIsTwoFactorEnabled() { return 0; }
intptr_t SteamAPI_ISteamUser_BSetDurationControlOnlineState() { return 0; }
intptr_t SteamAPI_ISteamUser_DecompressVoice() { return 0; }
intptr_t SteamAPI_ISteamUser_EndAuthSession() { return 0; }
intptr_t SteamAPI_ISteamUser_GetAuthTicketForWebApi() { return 0; }
intptr_t SteamAPI_ISteamUser_GetAvailableVoice() { return 0; }
intptr_t SteamAPI_ISteamUser_GetDurationControl() { return 0; }
intptr_t SteamAPI_ISteamUser_GetEncryptedAppTicket() { return 0; }
intptr_t SteamAPI_ISteamUser_GetGameBadgeLevel() { return 0; }
intptr_t SteamAPI_ISteamUser_GetHSteamUser() { return 0; }
intptr_t SteamAPI_ISteamUser_GetMarketEligibility() { return 0; }
intptr_t SteamAPI_ISteamUser_GetPlayerSteamLevel() { return 0; }
intptr_t SteamAPI_ISteamUser_GetUserDataFolder() { return 0; }
intptr_t SteamAPI_ISteamUser_GetVoice() { return 0; }
intptr_t SteamAPI_ISteamUser_GetVoiceOptimalSampleRate() { return 0; }
intptr_t SteamAPI_ISteamUser_InitiateGameConnection_DEPRECATED() { return 0; }
intptr_t SteamAPI_ISteamUser_RequestEncryptedAppTicket() { return 0; }
intptr_t SteamAPI_ISteamUser_RequestStoreAuthURL() { return 0; }
intptr_t SteamAPI_ISteamUser_StartVoiceRecording() { return 0; }
intptr_t SteamAPI_ISteamUserStats_AttachLeaderboardUGC() { return 0; }
intptr_t SteamAPI_ISteamUserStats_DownloadLeaderboardEntries() { return 0; }
intptr_t SteamAPI_ISteamUserStats_DownloadLeaderboardEntriesForUsers() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetAchievementProgressLimitsFloat() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetAchievementProgressLimitsInt32() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetDownloadedLeaderboardEntry() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetLeaderboardDisplayType() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetLeaderboardEntryCount() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetLeaderboardName() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetLeaderboardSortMethod() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetMostAchievedAchievementInfo() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetNextMostAchievedAchievementInfo() { return 0; }
intptr_t SteamAPI_ISteamUserStats_GetNumberOfCurrentPlayers() { return 0; }
intptr_t SteamAPI_ISteamUserStats_UploadLeaderboardScore() { return 0; }
intptr_t SteamAPI_ISteamUser_StopVoiceRecording() { return 0; }
intptr_t SteamAPI_ISteamUser_TerminateGameConnection_DEPRECATED() { return 0; }
intptr_t SteamAPI_ISteamUser_TrackAppUsageEvent() { return 0; }
intptr_t SteamAPI_ISteamUtils_GetAPICallFailureReason() { return 0; }
intptr_t SteamAPI_ISteamUtils_GetAPICallResult() { return 0; }
intptr_t SteamAPI_ISteamUtils_GetConnectedUniverse() { return 0; }
intptr_t SteamAPI_ISteamUtils_GetIPCCallCount() { return 0; }
intptr_t SteamAPI_ISteamUtils_GetIPv6ConnectivityState() { return 0; }
intptr_t SteamAPI_ISteamUtils_IsAPICallCompleted() { return 0; }
intptr_t SteamAPI_ISteamUtils_IsSteamChinaLauncher() { return 0; }
intptr_t SteamAPI_ISteamUtils_SetGameLauncherMode() { return 0; }
intptr_t SteamAPI_ISteamUtils_SetVRHeadsetStreamingEnabled() { return 0; }
intptr_t SteamAPI_ISteamUtils_StartVRDashboard() { return 0; }
intptr_t SteamAPI_ISteamVideo_GetOPFSettings() { return 0; }
intptr_t SteamAPI_ISteamVideo_GetOPFStringForApp() { return 0; }
intptr_t SteamAPI_ISteamVideo_GetVideoURL() { return 0; }
intptr_t SteamAPI_ISteamVideo_IsBroadcasting() { return 0; }
